# Loading in necessary modules and functions
from __future__ import annotations
from pyspark.sql import DataFrame
from pyspark.sql import functions as F
from functools import reduce
from pyspark.sql.types import *
import pandas as pd


class SparkDataCheck: 
    '''
    A class designed to assist the user in validating a PySpark.sql dataframe,
    stored as the attribute df. 
    
    In addition to using __init__ to directly initialize the class with a 
    pre-existing PySpark.sql dataframe, there are two convenient class methods
    to create an object of class SparkDataCheck:
        - from_csv: a class method that takes in the Spark session (spark) and
        a file path to a csv data file (csv_path) as inputs to create the object,
        storing the dataset as a PySpark.sql dataframe in df
        - from_pddf: a class method that takes in the Spark session (spark) and
        a pandas dataframe (pd_df) as inputs to create the object, storing the 
        dataset as a PySpark.sql dataframe in df
        
    Note that these two class methods will not produce identical results because
    pandas and PySpark.sql exhibit different csv-to-dataframe behaviors. 
    
    Methods:
        - in_range: a method that takes in a numeric column (column) as well as a
        lower bound (lower) and/or upper bound (upper), then returns the updated
        SparkDataCheck object itself with a new Boolean column in df indicating whether
         or not the input column's value is in the user-defined range
        - in_set: a method that takes in a string column (column) as well as a list of
        levels for the column and an optional set tag (tag), then returns the updated
        SparkDataCheck object with a new Boolean column in df (with tag incorporated 
        in the name) indicating whether or not the input column's value is in the set 
        of levels
        - is_null: a method that takes in a column (column) and returns the 
        updated SparkDataCheck object with a new Boolean column in df indicating 
        whether or not the input column's value is NULL
        - calc_min_max: a method that optionally takes in a numeric column (column)
        and a grouping column (groupby; can be any type but should conceptually be 
        categorical) and returns the following based on user inputs:
            - if neither input is provided, the method returns a pandas dataframe
            of minimum and maximum values for each numeric column in df
            - if only groupby is provided, the method returns a pandas dataframe
            of minimum and maximum values for each numeric column in df at each level of
            groupby
            - if only column is provided, the method returns a pandas dataframe
            of the unconditional minimum and maximum for that numeric column
            - If both column and groupby are provided, the method returns a pandas
            dataframe of the minimum and maximum values for column at each 
            level of groupby
        - count_combos: a method that takes in up to two string columns 
        (column1 and column2) and returns the following based on the number of 
        input columns:
            - if only column1 input, the method returns a pandas dataframe
            with counts for each level of the input column
            - if both column1 and column2 are input, the method returns a pandas
            dataframe with counts for each combination of levels across the
            two input columns
            
    Note that the methods assume missing values are assigned a NULL, not NaN or
    any other missing code. When a value is NULL, the Boolean columns generated by in_range
    and in_set will also be NULL.
    '''

    # Initializing the class
    def __init__(self, df: DataFrame):
        # Creating a df attribute containing the dataframe input
        self.df = df
 
    ########################################################################
    # Class methods
        
    # Constructing method for creating a new instance while reading in a csv
    @classmethod
    def from_csv(cls, spark, csv_path: str): 
        # Reading in the file as a SQL dataframe
        # Note: We are assuming the file has headers
        df = spark.read.load(csv_path,
                     format="csv", 
                     sep=",", 
                     inferSchema="true", 
                     header="true")
        
        # Returning the dataset as an object of the SparkDataCheck class
        return cls(df)
    
    # Constructing method for creating a new instance from a pandas dataframe
    @classmethod
    def from_pddf(cls, spark, pd_df):
        # Converting pandas dataframe to SQL-style dataframe
        df = spark.createDataFrame(pd_df)
        
        # Returning the dataset as an object of the SparkDataCheck class
        return cls(df)
    
    ########################################################################
    # Methods
    
    # Constructing method that adds a boolean column indicating
    # whether the values of a pre-existing numeric column are within a given range
    def in_range(self, column: str, lower: float | None = None, upper: float | None = None): 
        # Confirming column is a numeric column
        if dict(self.df.dtypes)[column] not in ["float", "int", "long", "bigint", "double", 
                                                "integer"]:
            print("Column must be a numeric type")
            return self
        
        # Checking if neither upper or lower is provided
        # Note that by SQL rules, will return Null when value is Null
        if lower is None and upper is None:
            raise ValueError("At least one of lower and upper must be provided.")
        # If at least one provided, constructing new column name and column
        elif lower is None: # case when lower not specified
            new_var = column + "_below_" + str(upper)
            self.df = self.df.withColumn(new_var, self.df[column] <= upper)
        elif upper is None: # case when upper not specified
            new_var = column + "_above_" + str(lower)
            self.df = self.df.withColumn(new_var, self.df[column] >= lower)
        else: # case when both specified
            new_var = column + "_in_" + str(lower) + "_" + str(upper)
            self.df = self.df.withColumn(new_var, self.df[column].between(lower, upper))
            
        # Returning modified dataframe    
        return self
    
    # Constructing method that adds a boolean column indicating
    # whether the values of a pre-existing string column are in a given set
    # tag is the stub added to the new column's name for user reference
    def in_set(self, column: str, levels: list[str], tag: str | None = None):
        # Confirming column is a string column
        if dict(self.df.dtypes)[column] != "string":
            print("Column must be a string type")
            return self
        
        # Appending the boolean column indicating set inclusion (or not)
        # Note that by SQL rules, will return Null when value is Null
        if tag is None:
            self.df = self.df.withColumn(column + "_in_set", 
                                         self.df[column].isin(levels))
        else:
            self.df = self.df.withColumn(column + "_in_set_" + 
                                         tag, self.df[column].isin(levels))            
        
        # Returning the modified dataframe
        return self
    
    # Constructing method that adds a boolean column indicating
    # whether the values of a pre-existing column are Null or not
    def is_null(self, column: str):
        # Appending a boolean column indicating whether or not each value is Null
        self.df = self.df.withColumn(column + "_is_null", self.df[column].isNull())
        
        # Returning the modified dataframe
        return self
    
    # Constructing method to return min and max of user-provided numeric column
    # across any user-specified grouping variable
    # If no column specified, min and max returned across all numeric columns
    def calc_min_max(self, column: str | None = None, groupby: str | None = None):
        # Confirming column is a numeric column (when specified)
        # Returning None if not
        # Returning min's and max's if so
        if column is not None:
            if dict(self.df.dtypes)[column] not in ["float", "int", "long", "bigint", "double", 
                                                    "integer"]:
                print("Column must be a numeric type")
                return None 
            elif groupby is not None: # Conditional min and max case
                pd_df = self.df.groupBy(groupby).agg(F.min(column), 
                                                     F.max(column)).toPandas().sort_values(groupby)
            else: # Unconditional case
                pd_df = self.df.select(F.min(column), F.max(column)).toPandas()
        # Returning min's and max's for all numeric variables
        # when no columns specified
        else:
            # Capturing numeric variables 
            types = pd.DataFrame(self.df.dtypes, columns = ["variable", "type"])
            numcols = types[types.type.isin(["float", "int", "long", "bigint", "double", 
                                             "integer"])].variable
            
            # Generating min's and max's in unconditional case
            if groupby is None:
                # Generating min and max and capturing in a dataframe
                # Starting by creating an iteration counter
                iter = 0
            
                # Looping over numeric variables to concatenate their min's and max's in a pandas df
                for col in numcols:
                    if iter == 0:
                        pd_df = self.df.select(F.min(col), F.max(col)).toPandas()
                    else:
                        pd_df = pd.concat([pd_df, self.df.select(F.min(col), 
                                                                 F.max(col)).toPandas()], axis = 1)
                    
                    iter += 1
                        
            # Generating min's and max's for conditional case
            else:
                # Generating min and max and capturing in a dataframe
                # Starting by creating an iteration counter
                iter = 0

                # Looping over numeric variables to concatenate their min's and max's in a pandas df                
                for col in numcols:
                    if iter == 0:
                        pd_df = self.df.groupBy(groupby).agg(F.min(col), F.max(col)).toPandas()
                    else:
                        pd_df = pd.concat([pd_df, self.df.groupBy(groupby).agg(F.min(col), F.max(col)) \
                                           .toPandas().drop(columns = groupby)], axis = 1)
                    iter += 1
                    
                # Sorting by groupby
                pd_df = pd_df.sort_values(groupby)
                        
                        
        # Returning the resultant pandas dataframe of min's and max's
        return pd_df
    
    # Constructing method to return counts for levels of a single categorical variable or 
    # combinations of levels for two categorical variables
    def count_combos(self, column1: str, column2: str | None = None):
        # Confirming at least one of the two input columns is actually a string
        if dict(self.df.dtypes)[column1] != "string":
            # If first column not, check second column (if not None)
            if column2 is None or dict(self.df.dtypes)[column2] != "string":
                # If no string columns provided, print message and return None
                print("Each input column is numeric, but should be string")
                return None 
            
            # Case when second column is a string
            else: 
                # Printing message indicating first column numeric
                print("column1 is numeric, should be string")
                
                # Generating counts for each level of column2
                pd_df = self.df.groupBy(column2).count().toPandas()
        
        # Case when first column is a string
        else:
            # Case when second column not provided
            if column2 is None:
                # Generating counts for each level of column1
                pd_df = self.df.groupBy(column1).count().toPandas()
            
            # Case when second column is numeric
            elif dict(self.df.dtypes)[column2] != "string":
                # Printing message indicating second column numeric
                print("column2 is numeric, should be string")
                
                # Generating counts for each level of column1
                pd_df = self.df.groupBy(column1).count().toPandas()
                
            # Case when both columns are strings
            else:
                # Generating counts for each combination of levels
                pd_df = self.df.groupBy([column1, column2]).count().toPandas()
                
        # Returning the pandas data frame of counts
        return pd_df
    
    
        
            
            
        
    
    
        
        
        
        
    
    
        
        
    